person:
  FirstName: Sank
  lastName: Xie
  age: 24
  birth: 1997/01/01
  maps: {k1: v1,k2: v2}
  lists:
    - ssss
    - dddd
  dog:
    name: iii
    age: 2

spring:
  http:
    encoding:
      charset: UTF-8

